apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: infra-backstage
  namespace: backstage
  title: Backstage
  description: Backstage
  tags:
    - terraform
    - poc
    - test
spec:
  type: iac-repo
  owner: rca0
